# Generated by Django 5.1.4 on 2024-12-28 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0002_alter_datafile_file_sharedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharedfile',
            options={'ordering': ['-shared_at'], 'verbose_name': 'Shared File', 'verbose_name_plural': 'Shared Files'},
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expiry date'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='data_manager.datafile', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='shared_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Share date'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_files', to=settings.AUTH_USER_MODEL, verbose_name='Shared by'),
        ),
        migrations.AlterField(
            model_name='sharedfile',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_files', to=settings.AUTH_USER_MODEL, verbose_name='Shared with'),
        ),
    ]
